import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const app=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8');
function source(name){const start=app.search(new RegExp('(?:async )?function '+name+'\\('));assert.ok(start>=0,`missing ${name}`);const rest=app.slice(start);const end=rest.slice(1).search(/\n(?:async )?function /);return end<0?rest:rest.slice(0,end+1);}
function harness({missing=false,switchSession=false}={}){
 const refs=[{id:'a',tag:'@图1',type:'image',reference:'media://a',url:'blob:a'},{id:'b',tag:'@图2',type:'image',reference:'media://b',url:'blob:b'}];
 let session='one';const calls=[];const editor={value:'old',focus(){},dispatchEvent(){}};
 const ctx={promptReuseSnapshots:new Map([['snapshot',{prompt:'@图2看向@图1，@图2',refMediaList:refs}]]),clone:x=>structuredClone(x),state:{chatRefMediaList:[{id:'current'}]},el:{aiChatTextarea:editor},SessionSystem:{getActive:()=>({id:session})},activeLocalConversation:{id:'conv'},BackendClient:{validateGenerationReferences:async()=>{if(missing)throw Error('参考素材已失效');if(switchSession)session='two';},getReferencePreview:async r=>'blob:'+r.slice(8)},safeMediaUrl:s=>s,renderChatRefMediaList:o=>calls.push(o),setChatPromptEditorValue:(e,v)=>e.value=v,Event:class{},syncCreationSubmitButtonState(){}};
 vm.createContext(ctx);vm.runInContext(source('reusePromptMessage'),ctx);return {ctx,refs,calls,editor};
}
test('snapshot button captures media before composer clearing and does not persist it',()=>{const ctx={promptReuseSnapshots:new Map(),clone:x=>structuredClone(x),Date,Math};vm.createContext(ctx);vm.runInContext(source('messageReuseButton'),ctx);const refs=[{tag:'@图2',type:'image',reference:'media://b'}];const html=ctx.messageReuseButton('@图2',refs);refs[0].reference='changed';const id=html.match(/data-reuse-prompt="([^"]+)"/)[1];assert.equal(ctx.promptReuseSnapshots.get(id).refMediaList[0].reference,'media://b');assert.ok(!source('messageReuseButton').includes('localStorage'));});
test('text-only reuse works without attachments',async()=>{const h=harness();h.ctx.promptReuseSnapshots.set('text',{prompt:'纯文字\n第二行',refMediaList:[]});assert.equal(await h.ctx.reusePromptMessage('text'),true);assert.equal(h.editor.value,'纯文字\n第二行');assert.equal(h.ctx.state.chatRefMediaList.length,0);});
test('missing mention identity cannot degrade into plain text reuse',async()=>{const h=harness();h.ctx.promptReuseSnapshots.set('missing',{prompt:'@图1',refMediaList:[]});assert.equal(await h.ctx.reusePromptMessage('missing',{}),false);assert.equal(h.editor.value,'old');});
test('mixed video audio image references preserve original tags rather than current composer numbering',async()=>{const h=harness();h.ctx.promptReuseSnapshots.set('mixed',{prompt:'@图3 @图1 @图2 @图3',refMediaList:[{id:'v',tag:'@图1',type:'video',reference:'media://v'},{id:'a',tag:'@图2',type:'audio',reference:'media://a'},{id:'i',tag:'@图3',type:'image',reference:'media://i'}]});assert.equal(await h.ctx.reusePromptMessage('mixed'),true);assert.deepEqual(h.ctx.state.chatRefMediaList.map(x=>x.tag),['@图1','@图2','@图3']);});
test('reuse restores original prompt and ordered referenced materials without submitting',async()=>{const h=harness();const button={textContent:'复用',disabled:false};assert.equal(await h.ctx.reusePromptMessage('snapshot',button),true);assert.equal(h.editor.value,'@图2看向@图1，@图2');assert.deepEqual(h.ctx.state.chatRefMediaList.map(r=>r.id),['a','b']);assert.equal(h.calls[0].preserveTags,true);h.ctx.state.chatRefMediaList[0].id='edited';assert.equal(h.refs[0].id,'a');});
test('missing original media leaves current draft untouched and reports on the button',async()=>{const h=harness({missing:true});const b={textContent:'复用'};assert.equal(await h.ctx.reusePromptMessage('snapshot',b),false);assert.equal(h.editor.value,'old');assert.equal(h.ctx.state.chatRefMediaList[0].id,'current');assert.match(b.textContent,/素材|失效/);});
test('switching session during validation cannot overwrite the new draft',async()=>{const h=harness({switchSession:true});assert.equal(await h.ctx.reusePromptMessage('snapshot',{}),false);assert.equal(h.editor.value,'old');});
